### ISSUE TITLE
Util.doubleToCMTime crash

### ISSUE THREAD

**Issue by MihaMajcen** [bitmovin/bitmovin-analytics-collector-ios#37]
I'm getting crashes with live streams. Library crashes in BitmovinPlayerAdapter.swift, func onVideoDownloadQualityChanged(_ event: VideoDownloadQualityChangedEvent).

Fatal error: Double value cannot be converted to Int64 because it is either infinite or NaN. 

I've inspected app with debugger and found out that player.currentTime is NaN. 
Util.doubleToCMTime(double: player.currentTime)

**Comment by Tigraine** [comment]
Hi @MihaMajcen - we have just released v1.7.3 which fixes this issue.
Thank you so much for reporting this!
