### ISSUE TITLE
Fatal error: Double value cannot be converted to Int64 because it is either infinite or Na

### ISSUE THREAD

**Issue by seanliu1** [bitmovin/bitmovin-analytics-collector-ios#38]
BitmovinAnalyticsInternal line 64
`
            eventData.videoTimeEnd = Int64(CMTimeGetSeconds(timeEnd) * BitmovinAnalyticsInternal.msInSec)
`
Fatal error: Double value cannot be converted to Int64 because it is either infinite or Na

**Comment by Tigraine** [comment]
Hi, thanks for reporting. We are currently working on this and should be releasing a fix in the next few days
