### ISSUE TITLE
Directory not found warning when running pod install

### ISSUE THREAD

**Issue by ModernMantra** [bitmovin/bitmovin-analytics-collector-ios#51]
# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Build successfully with the pods without any warnings.

## What happened instead?

```
ld: warning: directory not found for option '-F/{PATH}/bitmovin-analytics-collector/Pods/*'
```
NOTE: Proposed solutions to delete search path for Project Settings found on stackoverflow and apple developer site did not work at all. The Example project found here on bitmovin github page has the same warning.

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.6.1 (20G224)
       Xcode : 13.2.1 (13C100)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : bitmovin-cocoapod-specs - git - https://github.com/bitmovin/cocoapod-specs.git @ e223d511bb86c28eb1b4a3551c7f070936d9cd5b

               cocoapods - git - https://github.com/CocoaPods/Specs.git @ 206d06c3bf1e8b630816ae1198d5944d0bf51ee6

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

## Environment

XCode 13.2.1
Macbook Pro Intel Core i7
macOS Big Sur

## Podfile

```
$tvos_version = '13.0'

$bitmovin_version = '1.24.0'
$bitmovin_source = 'https://github.com/bitmovin/bitmovin-analytics-collector-ios'

def pods
  platform :tvos, $tvos_version
  pod 'BitmovinAnalyticsCollector/Core', :git => $bitmovin_source, :tag => $bitmovin_version
  pod 'BitmovinAnalyticsCollector/AVPlayer', :git => $bitmovin_source, :tag => $bitmovin_version
end
```

**Comment by dweinber** [comment]
Hey @ModernMantra,
I tried to replicate this but haven't managed to do so. I updated my local copy of this repo to the latest, went into `Examples-BitmovinPlayerV3` and ran `pod install --repo-update` successfully. I'm also able to successfully build and run the iOS sample project. Any step I'm missing?

Further, I'm not sure I fully get the impact of this issue, besides printing the warning. Is this preventing from all dependencies to be installed, or from successfully building and running the application?

**Comment by dweinber** [comment]
If you have any questions or issues with this Analytics Collector or its examples, or you require other technical support for our services, please log in to your Bitmovin Dashboard at https://bitmovin.com/dashboard and create a new support case. Our team will get back to you as soon as possible 👍
